"""Password hashing, and the compatibility that lets it change.

Passwords are hashed with Argon2id. Before that they were bcrypt, and before
that bcrypt through passlib -- and the property that made each of those moves
safe, and that must keep holding, is that a hash written by the *old* code
still verifies under the new.

That is what most of this file is about. The hard-coded hashes below were
generated by the code that came before and are not to be regenerated: a hash
produced by the current code proves nothing about the old one. If a future
change breaks one of these tests, it has silently locked every existing user
out of the platform, and they will find out at the same moment as each other.

Run with:  cd backend && pytest tests/test_password_hashing.py -q
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("APP_ENV", "development")

from app.core.security import (  # noqa: E402
    hash_password,
    needs_rehash,
    verify_password,
)

# Generated by passlib==1.7.4 / bcrypt==4.0.1 for the password below, before
# passlib was removed. Do not regenerate it -- a hash produced by the current
# code proves nothing about the old one.
PASSLIB_HASH = "$2b$12$WiXBMGCu.cWBuhBIOJJuauuENuI7xPucg2HONG53dHlyJAXciEACq"
PASSLIB_PASSWORD = "Admin@12345"


def test_a_hash_written_by_passlib_still_verifies():
    assert verify_password(PASSLIB_PASSWORD, PASSLIB_HASH) is True


def test_a_wrong_password_against_a_passlib_hash_is_refused():
    assert verify_password("not-the-password", PASSLIB_HASH) is False


def test_a_new_hash_round_trips():
    hashed = hash_password(PASSLIB_PASSWORD)
    assert verify_password(PASSLIB_PASSWORD, hashed) is True
    assert verify_password("wrong", hashed) is False


def test_new_hashes_are_argon2id():
    """Not merely Argon2 -- the id variant specifically.

    Argon2 has three variants. Argon2i is hardened against side-channel timing
    attacks and weaker against GPUs; Argon2d is the reverse. Argon2id runs one
    pass of each, and is the one OWASP and RFC 9106 name for password storage.
    Getting this wrong is invisible in every functional test, because all three
    hash and verify perfectly well.
    """
    assert hash_password("anything").startswith("$argon2id$")


def test_a_bcrypt_hash_is_flagged_for_upgrade():
    """The mechanism that drains the old format away without a mass reset."""
    assert needs_rehash(PASSLIB_HASH) is True


def test_a_current_argon2_hash_is_not_flagged():
    """Otherwise every login would rewrite a row for no reason."""
    assert needs_rehash(hash_password("anything")) is False


def test_an_unreadable_hash_is_not_flagged_for_upgrade():
    """There is nothing to upgrade, and the login it belongs to already failed."""
    assert needs_rehash("") is False
    assert needs_rehash("$argon2id$not-really") is False


@pytest.mark.parametrize(
    "broken",
    [
        "",
        "not-a-hash",
        "$2b$",
        "$2b$12$short",
        "$2b$99$" + "x" * 53,
        "$1$md5$something",
        "$2b$12$" + "!" * 53,
        # And the same class of damage in the new format.
        "$argon2id$",
        "$argon2id$v=19$m=65536,t=2,p=1$truncated",
        "$argon2id$v=19$m=65536,t=2,p=1$" + "!" * 40,
    ],
)
def test_a_corrupt_hash_is_a_failed_login_not_a_crash(broken):
    """A corrupted row must fail that one login, not the worker.

    Worse than an exception: some malformed bcrypt shapes panic inside its Rust
    extension, and PanicException does not inherit from Exception, so no
    ordinary except catches it. The shape is checked before the value reaches
    the library. Argon2 raises an ordinary InvalidHash, which is caught -- both
    formats are covered here because either can be the thing in the column.
    """
    assert verify_password("anything", broken) is False


def test_a_password_longer_than_bcrypts_limit_still_works():
    """Argon2id reads the whole password; bcrypt read the first 72 bytes.

    Both must handle a long passphrase without raising. Under bcrypt that meant
    truncating explicitly, so a dependency changing its mind about over-long
    input could not stop someone signing in; under Argon2id there is no limit
    to truncate at.
    """
    long_password = "correct horse battery staple " * 10
    assert len(long_password.encode()) > 72
    hashed = hash_password(long_password)
    assert verify_password(long_password, hashed) is True


def test_two_long_passwords_differing_only_past_72_bytes_are_different():
    """The bug Argon2id removes, stated as a test.

    bcrypt reads 72 bytes and ignores the rest, so these two were the same
    password as far as the stored hash was concerned -- and anyone who knew the
    first could sign in as the holder of the second.
    """
    shared_prefix = "x" * 72
    first = shared_prefix + "alpha"
    second = shared_prefix + "omega"
    assert verify_password(second, hash_password(first)) is False


def test_two_hashes_of_the_same_password_differ():
    """Salted, so identical passwords do not produce identical rows."""
    assert hash_password("same") != hash_password("same")
