"""Password hashing, and the compatibility that lets it change.

passlib was removed in favour of calling bcrypt directly: no release since
2020, it read a private bcrypt attribute removed in 4.1 (which is why bcrypt
was pinned back to 4.0.1), and it imports the stdlib ``crypt`` module deleted
in Python 3.12+ -- while the backend Dockerfile already notes that Python 3.12
reaches end of life inside this platform's expected lifetime.

The property that made the swap safe, and that must keep holding, is that the
stored format did not change. The hash below was generated by passlib 1.7.4 and
is hard-coded on purpose: it is the evidence that a password set before the
swap still works after it. If a future change breaks this test, it has silently
locked every existing user out of the platform.

Run with:  cd backend && pytest tests/test_password_hashing.py -q
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("APP_ENV", "development")

from app.core.security import hash_password, verify_password  # noqa: E402

# Generated by passlib==1.7.4 / bcrypt==4.0.1 for the password below, before
# passlib was removed. Do not regenerate it -- a hash produced by the current
# code proves nothing about the old one.
PASSLIB_HASH = "$2b$12$WiXBMGCu.cWBuhBIOJJuauuENuI7xPucg2HONG53dHlyJAXciEACq"
PASSLIB_PASSWORD = "Admin@12345"


def test_a_hash_written_by_passlib_still_verifies():
    assert verify_password(PASSLIB_PASSWORD, PASSLIB_HASH) is True


def test_a_wrong_password_against_a_passlib_hash_is_refused():
    assert verify_password("not-the-password", PASSLIB_HASH) is False


def test_a_new_hash_round_trips():
    hashed = hash_password(PASSLIB_PASSWORD)
    assert verify_password(PASSLIB_PASSWORD, hashed) is True
    assert verify_password("wrong", hashed) is False


def test_the_stored_format_is_unchanged():
    """Same algorithm, same cost. A change here re-hashes nobody."""
    assert hash_password("anything").startswith("$2b$12$")


@pytest.mark.parametrize(
    "broken",
    [
        "",
        "not-a-hash",
        "$2b$",
        "$2b$12$short",
        "$2b$99$" + "x" * 53,
        "$1$md5$something",
        "$2b$12$" + "!" * 53,
    ],
)
def test_a_corrupt_hash_is_a_failed_login_not_a_crash(broken):
    """passlib absorbed a malformed hash; calling bcrypt directly does not.

    Worse than an exception: some shapes panic inside bcrypt's Rust extension,
    and PanicException does not inherit from Exception, so no ordinary except
    catches it. One corrupted password_hash row would take the worker down
    rather than failing that one login. The shape is checked before the value
    reaches the library.
    """
    assert verify_password("anything", broken) is False


def test_a_password_longer_than_bcrypts_limit_still_works():
    """bcrypt takes 72 bytes; 5.x raises where 4.x truncated silently.

    Truncating explicitly means a user with a long passphrase does not stop
    being able to sign in because a dependency changed its mind.
    """
    long_password = "correct horse battery staple " * 10
    assert len(long_password.encode()) > 72
    hashed = hash_password(long_password)
    assert verify_password(long_password, hashed) is True


def test_two_hashes_of_the_same_password_differ():
    """Salted, so identical passwords do not produce identical rows."""
    assert hash_password("same") != hash_password("same")
