"""CPM data wipe service.

Deletes only CPM-derived operational data so an admin can start fresh with
a new import. Deliberately preserves: users, roles, contractors, provinces,
regions, problem categories, monthly plans, and the audit log itself (per the
agreed scope -- this is NOT a full factory reset).

Deletion order matters (children before parents) since we do explicit,
auditable deletes rather than relying on database-level CASCADE -- this
keeps the operation fully visible and reviewable in one place.

Every wiped table is declared once, in order, in :data:`WIPE_ORDER`. Twice a
new table referencing CPM data (acceptance submissions, then the Mojri
tracker) was added without a line here, and each time the wipe failed its FK
check on PostgreSQL and rolled back as "Erase failed". The tests in
``tests/test_data_wipe.py`` now walk the schema and fail if any table hanging
off ``sites``/``work_items``/``villages`` is missing from the list, or if a
child is ordered after its parent.
"""
from __future__ import annotations

from sqlalchemy import Table
from sqlalchemy.orm import Session

from app.models.acceptance import (
    Acceptance,
    CpmChangeRequest,
    CpmImportBatch,
    Letter,
    MonthlySnapshot,
    SnapshotContractorCompletion,
    letter_villages,
)
from app.models.acceptance_workflow import (
    AcceptanceEvidence,
    AcceptanceSubmission,
    AcceptanceSubmissionTech,
)
from app.models.health_check import HcAssignment, HcRemediation, HcTask, HcTaskTechnology
from app.models.mojri import MojriImportRun, MojriTrackerStatus
from app.models.workitem import (
    Assignment,
    DriveTest,
    DriveTestEvidence,
    HealthCheck,
    Site,
    Village,
    WorkItem,
)

# The exact confirmation phrase the caller must supply. Enforced both here
# (defense in depth) and in the API layer, so a direct API call without the
# UI can't trigger this by accident.
REQUIRED_CONFIRMATION_PHRASE = "ERASE ALL CPM DATA"

#: Every table the wipe empties, children before parents, as
#: (label in the result, table). The labels are the API's ``deleted`` keys and
#: are recorded in the audit log, so they never change once shipped.
WIPE_ORDER: tuple[tuple[str, Table], ...] = (
    # Letters and acceptance (the many-to-many join table first).
    ("letter_villages", letter_villages),
    ("letters", Letter.__table__),
    ("acceptances", Acceptance.__table__),
    # Acceptance submission workflow: what a contractor/coordinator files, so
    # any village with acceptance history has these.
    ("acceptance_evidence", AcceptanceEvidence.__table__),
    ("acceptance_submission_techs", AcceptanceSubmissionTech.__table__),
    ("acceptance_submissions", AcceptanceSubmission.__table__),
    # Health-check workflow. hc_remediations references hc_tasks (and
    # work_items) with no DB-level cascade, so it goes before hc_tasks.
    ("hc_task_technologies", HcTaskTechnology.__table__),
    ("hc_remediations", HcRemediation.__table__),
    ("hc_tasks", HcTask.__table__),
    ("hc_assignments", HcAssignment.__table__),
    ("health_checks", HealthCheck.__table__),
    ("assignments", Assignment.__table__),
    # Explicit even though its FK cascades: the wipe is reviewable here, not
    # in a migration's ON DELETE clause.
    ("drive_test_evidence", DriveTestEvidence.__table__),
    ("drive_tests", DriveTest.__table__),
    # Mojri tracker. Village ids are regenerated by the next import, so a
    # surviving status would attach to whichever new village reused the id.
    ("mojri_tracker_status", MojriTrackerStatus.__table__),
    ("mojri_import_runs", MojriImportRun.__table__),
    # The CPM hierarchy itself.
    ("villages", Village.__table__),
    ("cpm_change_requests", CpmChangeRequest.__table__),
    ("work_items", WorkItem.__table__),
    ("sites", Site.__table__),
    ("cpm_import_batches", CpmImportBatch.__table__),
    # The per-contractor movement rows hang off monthly_snapshots.
    ("snapshot_contractor_completions", SnapshotContractorCompletion.__table__),
    ("monthly_snapshots", MonthlySnapshot.__table__),
)


def wipe_cpm_data(db: Session) -> dict[str, int]:
    """Delete all CPM-imported data. Returns a dict of deleted row counts.

    Caller is responsible for checking the confirmation phrase before
    invoking this -- see the API endpoint for that check.
    """
    return {label: db.execute(table.delete()).rowcount for label, table in WIPE_ORDER}
